---
:ovftool:  '/usr/bin/ovftool'
:pe_version: '3.1.0'
:pe_release_url: 'https://s3.amazonaws.com/pe-builds/released'


# This is runtime informmation, will be split out
:vmos: :centos
:vmtype: :training

# Hardcoded based on type
:vm_hostname:
  :training: 'training.puppetlabs.vm'
  :learn: 'learn.localdomain'

# done for either centos or debian
:common:
  :git_clone:
    - :src: 'git://github.com/puppetlabs/puppet.git'
      :dest: ':CACHE_DIR:/puppet.git'
      :branch: 'master'
    - :src: 'git://github.com/puppetlabs/hiera.git'
      :dest: ':CACHE_DIR:/hiera.git'
      :branch: 'master'
    - :src: 'git://github.com/puppetlabs/facter.git'
      :dest: ':CACHE_DIR:/facter.git'
      :branch: 'master'

    # this is the "secret sauce"
    - :src: 'git@github.com:puppetlabs/puppetlabs-training-bootstrap.git'
      :dest: ':CACHE_DIR:/puppetlabs-training-bootstrap.git'
      :branch: 'master'

# Centos 6.4 configuration.  How should I handle the versions?
:centos:
  :name: 'Centos'
  :pe_install_suffix: '-el-6-i386'
  :iso_glob: 'CentOS-*'
  :iso_url: 'http://mirror.tocici.com/centos/6/isos/i386/CentOS-6.4-i386-bin-DVD1.iso'
  :build_files:
    - 'isolinux.cfg'
    - 'ks.cfg'
  :download_files:
    - :src: 'http://mirrors.cat.pdx.edu/epel/6/i386/epel-release-6-8.noarch.rpm'
      :dest: ":CACHE_DIR:/epel-release.rpm"
    - :src: http://yum-enterprise.puppetlabs.com/el/6/extras/i386/puppetlabs-enterprise-release-extras-6-2.noarch.rpm'
      :dest: ':CACHE_DIR:/puppetlabs-enterprise-release-extras.rpm'
  :iso_files:
    - :src: ':BUILD_DIR:/centos/isolinux.cfg'
      :dest: '/isolinux/isolinux.cfg'
    - :src: ':BUILD_DIR:/centos/ks.cfg'
      :dest: '/puppet/ks.cfg'
    - :src: ':CACHE_DIR:/epel-release.rpm'
      :dest: '/puppet/epel-release.rpm'
    - :src: ':CACHE_DIR:/puppetlabs-enterprise-release-extras.rpm'
      :dest: '/puppet/puppetlabs-enterprise-release-extras.rpm'
    - :src: ':CACHE_DIR:/puppet.git'
      :dest: '/puppet/puppet.git'
    - :src: ':CACHE_DIR:/facter.git'
      :dest: '/puppet/facter.git'
    - :src: ':CACHE_DIR:/hiera.git'
      :dest: '/puppet/hiera.git'


# this has not been tested, looks like site only has 7+
:debian:
  :name: 'debian'
  :pe_install_suffix: '-debian-6-i386'
  :iso_glob: 'debian-*'
  :iso_url: 'http://hammurabi.acc.umu.se/debian-cd/6.0.6/i386/iso-cd/debian-6.0.6-i386-CD-1.iso'
  :build_files:
    - 'isolinux.cfg'
    - 'preseed.cfg'
  :iso_files:
    - :src: ':BUILD_DIR:/debian/isolinux.cfg'
      :dest: '/isolinux/isolinux.cfg'
    - :src: ':BUILD_DIR:/debian/preseed.cfg'
      :dest: '/puppet/ks.cfg'
    - :src: ':CACHE_DIR:/puppetlabs-enterprise-release-extras.rpm'
      :dest: '/puppet/puppetlabs-enterprise-release-extras.rpm'
    - :src: ':CACHE_DIR:/puppet.git'
      :dest: '/puppet/puppet.git'
    - :src: ':CACHE_DIR:/facter.git'
      :dest: '/puppet/facter.git'
    - :src: ':CACHE_DIR:/hiera.git'
      :dest: '/puppet/hiera.git'
